### PR TITLE
HMap deriving Typeable

### PR DESCRIPTION
**Pull request by pmlodawski**
Hi, I made HMap deriving Typeable, it is useful in some cases including mine ;)

### CODE REVIEW

**Comment by mikusp** [comment]
+1, it would be useful for me as well.

**Comment by kgadek** [comment]
Any ETA on this one?

**Comment by atzeus** [comment]
ETA: Now. Sorry it took so long :)

**Comment by atzeus** [comment]
It's out :) https://hackage.haskell.org/package/HMap-1.2.6

**Comment by pmlodawski** [comment]
Cool, thanks!

**Comment by kgadek** [comment]
:+1: :)

**Pull request merged**
