### PR TITLE
Added deleteUnique function and Unique getter to HKey

### PR DESCRIPTION
**Pull request by pmlodawski**
Added a possibility to get `Unique` from keys and use it to delete values from `HMap`. `Unique` values because of its common type can make managing items in HMap easier

### CODE REVIEW

**Comment by atzeus** [comment]
Is this still necessary, or is the problem solved by removing weak references?

**Comment by pmlodawski** [comment]
This is optional, it just make easier to manage things in HMap

**Comment by atzeus** [comment]
Ok, cheers!

**Comment by pmlodawski** [comment]
Cool, thanks for accepting all the pull requests! :)

**Pull request merged**
